import { pickLanguage } from '../../core/i18n/i18n';
import { Badge } from './Badge';
import type { Severity } from '../../core/types/wms';
import { useWorkspace } from '../../core/workspace/workspace';

const severityMap: Record<string, Severity> = {
  Available: 'good',
  Connected: 'good',
  Shipped: 'good',
  Packed: 'good',
  Done: 'good',
  Dokončeno: 'good',
  Reserved: 'warning',
  Allocated: 'warning',
  Picking: 'warning',
  Claimed: 'warning',
  'In progress': 'warning',
  'Na rampě': 'warning',
  'Přijímá se': 'warning',
  Plánováno: 'neutral',
  Blocked: 'critical',
  Quarantine: 'critical',
  Exception: 'critical',
  Rush: 'critical',
  Idle: 'neutral',
  Receiving: 'warning',
  Outbound: 'warning',
  Draft: 'neutral',
  Ready: 'good',
  Running: 'warning',
  Completed: 'good',
  Sandbox: 'neutral',
  'Label ready': 'good',
  Packing: 'warning',
  'At risk': 'critical',
  Medium: 'warning',
  Fast: 'good',
  Online: 'good',
  Pause: 'warning',
  Open: 'neutral',
  New: 'neutral',
  Unknown: 'neutral',
  OPEN: 'neutral',
  WAITING: 'warning',
  READY: 'good',
  IN_PROGRESS: 'warning',
  DONE: 'good',
  COMPLETED: 'good',
  BLOCKED: 'critical',
  QUEUED: 'warning',
  CLAIMED: 'warning',
  PRINTING: 'warning',
  PRINTED: 'good',
  FAILED: 'critical',
  OFFLINE: 'critical',
  ONLINE: 'good',
  CUSTOM: 'neutral',
};

const labelMap: Record<string, string> = {
  Available: 'Dostupné',
  Connected: 'Připojeno',
  Shipped: 'Odesláno',
  Packed: 'Zabaleno',
  Done: 'Hotovo',
  Reserved: 'Rezervováno',
  Allocated: 'Alokováno',
  Picking: 'Vychystává se',
  Claimed: 'Převzato',
  'In progress': 'Probíhá',
  'Na rampě': 'Na rampě',
  'Přijímá se': 'Přijímá se',
  Plánováno: 'Plánováno',
  Blocked: 'Blokováno',
  Quarantine: 'Karanténa',
  Exception: 'Výjimka',
  Rush: 'Urgentní',
  Idle: 'Volno',
  Receiving: 'Příjem',
  Outbound: 'Výdej',
  Draft: 'Návrh',
  Ready: 'Připraveno',
  Running: 'Běží',
  Completed: 'Dokončeno',
  Sandbox: 'Testovací',
  'Label ready': 'Štítek připraven',
  Packing: 'Balí se',
  'At risk': 'V riziku',
  Medium: 'Střední',
  Fast: 'Rychlé',
  Online: 'V provozu',
  Pause: 'Pauza',
  Open: 'Otevřeno',
  New: 'Nové',
  Unknown: 'Neznámé',
  OPEN: 'Otevřeno',
  WAITING: 'Čeká',
  READY: 'Připraveno',
  IN_PROGRESS: 'Probíhá',
  DONE: 'Hotovo',
  COMPLETED: 'Dokončeno',
  BLOCKED: 'Blokováno',
  QUEUED: 'Ve frontě',
  CLAIMED: 'Převzato',
  PRINTING: 'Tiskne se',
  PRINTED: 'Vytištěno',
  FAILED: 'Chyba',
  OFFLINE: 'Odpojeno',
  ONLINE: 'Připojeno',
  CUSTOM: 'Vlastní',
};

const englishLabelMap: Record<string, string> = {
  Available: 'Available',
  Connected: 'Connected',
  Shipped: 'Shipped',
  Packed: 'Packed',
  Done: 'Done',
  Dokončeno: 'Done',
  Reserved: 'Reserved',
  Allocated: 'Allocated',
  Picking: 'Picking',
  Claimed: 'Claimed',
  'In progress': 'In progress',
  'Na rampě': 'At dock',
  'Přijímá se': 'Receiving',
  Plánováno: 'Planned',
  Blocked: 'Blocked',
  Quarantine: 'Quarantine',
  Exception: 'Exception',
  Rush: 'Rush',
  Idle: 'Idle',
  Receiving: 'Receiving',
  Outbound: 'Outbound',
  Draft: 'Draft',
  Ready: 'Ready',
  Running: 'Running',
  Completed: 'Completed',
  Sandbox: 'Sandbox',
  'Label ready': 'Label ready',
  Packing: 'Packing',
  'At risk': 'At risk',
  Medium: 'Medium',
  Fast: 'Fast',
  Online: 'Online',
  Pause: 'Paused',
  Open: 'Open',
  New: 'New',
  Unknown: 'Unknown',
  OPEN: 'Open',
  WAITING: 'Waiting',
  READY: 'Ready',
  IN_PROGRESS: 'In progress',
  DONE: 'Done',
  COMPLETED: 'Completed',
  BLOCKED: 'Blocked',
  QUEUED: 'Queued',
  CLAIMED: 'Claimed',
  PRINTING: 'Printing',
  PRINTED: 'Printed',
  FAILED: 'Failed',
  OFFLINE: 'Offline',
  ONLINE: 'Online',
  CUSTOM: 'Custom',
};

const ukrainianLabelMap: Record<string, string> = {
  Available: 'Доступно',
  Connected: 'Підключено',
  Shipped: 'Відправлено',
  Packed: 'Запаковано',
  Done: 'Готово',
  Dokončeno: 'Готово',
  Reserved: 'Зарезервовано',
  Allocated: 'Алоковано',
  Picking: 'Відбір',
  Claimed: 'Прийнято',
  'In progress': 'Виконується',
  'Na rampě': 'На рампі',
  'Přijímá se': 'Прийом',
  Plánováno: 'Заплановано',
  Blocked: 'Заблоковано',
  Quarantine: 'Карантин',
  Exception: 'Виняток',
  Rush: 'Терміново',
  Idle: 'Вільно',
  Receiving: 'Приймання',
  Outbound: 'Видача',
  Draft: 'Чернетка',
  Ready: 'Готово',
  Running: 'Виконується',
  Completed: 'Завершено',
  Sandbox: 'Тест',
  'Label ready': 'Етикетка готова',
  Packing: 'Пакується',
  'At risk': 'Ризик',
  Medium: 'Середній',
  Fast: 'Швидко',
  Online: 'Онлайн',
  Pause: 'Пауза',
  Open: 'Відкрито',
  New: 'Нове',
  Unknown: 'Невідомо',
  OPEN: 'Відкрито',
  WAITING: 'Очікує',
  READY: 'Готово',
  IN_PROGRESS: 'Виконується',
  DONE: 'Готово',
  COMPLETED: 'Завершено',
  BLOCKED: 'Заблоковано',
  QUEUED: 'У черзі',
  CLAIMED: 'Прийнято',
  PRINTING: 'Друкується',
  PRINTED: 'Надруковано',
  FAILED: 'Помилка',
  OFFLINE: 'Офлайн',
  ONLINE: 'Онлайн',
  CUSTOM: 'Власний',
};

export function StatusPill({ value }: { value: string }) {
  const { language } = useWorkspace();
  const labels = pickLanguage(language, { cs: labelMap, en: englishLabelMap, ua: ukrainianLabelMap });
  return <Badge tone={severityMap[value] ?? 'neutral'}>{labels[value] ?? value}</Badge>;
}
